#!/bin/bash
fio -direct=1 -iodepth=$1 -rw=randwrite -ioengine=libaio -bs=4k -size=20G -numjobs=1 -runtime=1000 -group_reporting -filename=iotest -name=20G.libaio.randwrite.iodepth$1.numjobs1 --output=20G.libaio.randwrite.iodepth$1.numjobs1.log
